<?php

declare(strict_types=1);

namespace App\Controller\Admin;

use App\Entity\Post;
use App\Repository\PostRepository;
use Doctrine\ORM\EntityManagerInterface;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;
use EasyCorp\Bundle\EasyAdminBundle\Field\AssociationField;
use EasyCorp\Bundle\EasyAdminBundle\Field\ImageField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextEditorField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextField;

class PostCrudController extends AbstractCrudController
{
    public function __construct(
        private readonly PostRepository $repository
    ) {
    }

    public static function getEntityFqcn(): string
    {
        return Post::class;
    }

    /**
     * @param Post $entityInstance
     */
    public function updateEntity(EntityManagerInterface $entityManager, $entityInstance): void
    {
        parent::updateEntity($entityManager, $entityInstance); // TODO: Change the autogenerated stub
    }

    public function configureFields(string $pageName): iterable
    {
        return [
            TextField::new('name'),
            TextEditorField::new('description'),
            AssociationField::new('owner'),
            ImageField::new('file')
                ->setUploadedFileNamePattern('files/[slug]-[contenthash].[extension]')
                ->setUploadDir('public/files')
                ->setRequired(false),
            AssociationField::new('postCategories')
                ->setFormTypeOption('by_reference', false),
            AssociationField::new('teaserCategories')
                ->setFormTypeOption('by_reference', false),
        ];
    }
}
